//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWebSpa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atiende
    {
        public long ID_Empleado { get; set; }
        public long ID_Cliente { get; set; }
        public long ID_Reserva { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
