//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWebSpa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public long IDInventario { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
